# This is a basic workflow to help you get started with Actions

name: Checkout

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          path: play
          
      - uses: actions/checkout@v3
        with:
          repository: gal-halevi/odin-landing-page
          path: page
          
      - uses: actions/checkout@v3
        with:
          repository: gal-halevi/odin-recipes
          path: recipe
          
      - name: Verify workspace
        run: ls -l ${{ github.workspace }}
          
      - name: Verify play
        run: ls -l ${{ github.workspace }}/play
        
      - name: Verify page
        run: ls -l ${{ github.workspace }}/page
        
      - name: Verify recipe
        run: ls -l ${{ github.workspace }}/recipe
          
