name: Checkout manifest
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  Checkout-Manifest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: gal-halevi/reusable-workflows
        path: reusable-workflows
    - uses: actions/checkout@v3
      with:
        repository: gal-halevi/deploy-to-azure
        path: deploy-to-azure
