# This is a basic workflow to help you get started with Actions

name: Checkout-Matrix

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  REPO_NAME: ${{ github.event.repository.name }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkout:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repos: [$REPO_NAME, "odin-landing-page", "odin-recipes"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          repository: gal-halevi/${{ matrix.repos }}
          path: ${{ matrix.repos }}
          
      - name: Verify workspace
        run: ls -l ${{ github.workspace }}/${{ matrix.repos }}
          
