name: Add label
on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        type: string
        required: true
jobs:
  AddLabel:
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ inputs.pull_request_number }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Get Pull reuqest
        run: | 
          sleep 5
          PR=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER)
          echo $PR | jq
          echo "MERGEABLE=$(echo $PR | jq -r '.mergeable_state')" >> "$GITHUB_ENV"

      - run: echo "MERGEABLE=$MERGEABLE"

      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Add Label
        if: env.MERGEABLE == 'clean'
        run: gh pr edit $PR_NUMBER --add-label "Ready for merge"

      - name: Remove Label
        if: env.MERGEABLE != 'clean'
        run: gh pr edit $PR_NUMBER --remove-label "Ready for merge"
