name: Python lint
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8' 

      - name: Install flake8
        run: |
          pip install flake8
          pip list

      - name: Run Lint
        run:
          flake8 $(git diff --name-only origin ${{ github.base_ref }} | grep .py)
          
