name: Python lint
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install python2.7 & pip
        run: |
          sudo apt -y install python2.7
          curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
          python2.7 get-pip.py

      - name: Install flake8
        run: |
          pip install flake8 pep8-naming==0.12.1 flake8-builtins==1.5.3 flake8-comprehensions
          python2.7 -m pip list

      - name: Run Lint
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          FOO=$(git diff --diff-filter=d --name-only origin/${{ github.base_ref }} | grep .py)
