name: Ready For Merge
on:
  pull_request_review:
    types: ['submitted']
jobs:
  PullRequestMergable:
    runs-on: ubuntu-latest
    env:
      REPO: ${{ github.repository }}
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Print the Github Context
        shell: bash
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          
      - name: Get Pull reuqest
        run: | 
          sleep 10
          PR=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$REPO/pulls/$PR_NUMBER)
          echo $PR | jq
          echo "MERGEABLE=$(echo $PR | jq '.mergeable_state')" >> "$GITHUB_ENV"
          
      - name: Checkout repo
        if: env.MERGEABLE == 'clean'
        uses: actions/checkout@v3
      
      - name: Create Label
        if: env.MERGEABLE == 'clean'
        run: gh pr edit $PR_NUMBER --add-label "Ready for merge"
