name: Ready For Merge
on:
  pull_request_review:
    types: ['submitted']
jobs:
  PullRequestMergable:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Github Context
        shell: bash
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Pull reuqest
        run: | 
          PR = $(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/$GITHUB_REPOSITORY/pulls/$GITHUB_EVENT_NUMBER)
          echo $PR
          echo "MERGEABLE=$(echo $PR | jq '.mergeable_state')" >> "$GITHUB_ENV"
          
      - name: Create Label
        if: ${{ ENV.MERGEABLE }} == "clean"
        run: gh pr edit ${{ github.event.number }} --add-label "Ready for merge"
