name: Ready For Merge
on:
  pull_request_review:
    types: ['submitted']
jobs:
  PullRequestMergable:
    if: github.event.review.state != 'commented'
    runs-on: ubuntu-latest
    env:
      PR_NUMBER: ${{ github.event.pull_request.number }}
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Print the Github Context
        shell: bash
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - uses: actions/checkout@v3
          
      - name: Trigger workflow
        continue-on-error: true
        run: |
          echo '{"pull_request_number":"${{ github.event.pull_request.number }}"}'
          echo '{"pull_request_number":"${{ github.event.pull_request.number }}"}' | gh workflow run create_label.yml --json
