name: Release
on:
  workflow_dispatch:

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: echo "Build"

      - name: Increment version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          VER=$(cat version)
          VER=$((VER+=1))
          echo $VER > version
          git add -u
          git commit -m "increment version $VER"
          git push -f
          echo "VERSION=$VER" >> "$GITHUB_ENV"

      - name: Create Release & Notes
        run: gh release create v1.2.$VERSION --generate-notes
